# Generated by Django 5.2.11 on 2026-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_migrate_tenant_workspaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantschema",
            name="state",
            field=models.CharField(
                choices=[
                    ("provisioning", "Provisioning"),
                    ("active", "Active"),
                    ("materializing", "Materializing"),
                    ("expired", "Expired"),
                    ("teardown", "Teardown"),
                    ("failed", "Failed"),
                ],
                default="provisioning",
                max_length=20,
            ),
        ),
    ]
