import { useEffect, useCallback } from "react"
import { Loader2 } from "lucide-react"
import { useAppStore } from "@/store/store"
import { useNetworkStatus } from "@/hooks/useNetworkStatus"
import { ArtifactList } from "./ArtifactList"
import type { ArtifactSummary } from "@/store/artifactSlice"

export function ArtifactsPage() {
  const artifacts = useAppStore((s) => s.artifacts)
  const artifactsStatus = useAppStore((s) => s.artifactsStatus)
  const artifactSearch = useAppStore((s) => s.artifactSearch)
  const {
    fetchArtifacts,
    updateArtifact,
    deleteArtifact,
    setArtifactSearch,
  } = useAppStore((s) => s.artifactActions)

  const { status: networkStatus } = useNetworkStatus()

  useEffect(() => {
    fetchArtifacts({
      search: artifactSearch || undefined,
    })
  }, [artifactSearch, fetchArtifacts])

  const handleSearchChange = useCallback((search: string) => {
    setArtifactSearch(search)
  }, [setArtifactSearch])

  const handleUpdate = useCallback(async (item: ArtifactSummary, data: { title?: string; description?: string }) => {
    await updateArtifact(item.id, data)
  }, [updateArtifact])

  const handleDelete = useCallback(async (item: ArtifactSummary) => {
    await deleteArtifact(item.id)
  }, [deleteArtifact])

  return (
    <div className="container mx-auto px-8 py-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold">Artifacts</h1>
        <p className="text-muted-foreground">
          Visualizations and content generated by the AI agent
        </p>
      </div>

      {/* Loading state */}
      {artifactsStatus === "loading" && (
        <div className="flex items-center gap-2 text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading artifacts...
        </div>
      )}

      {/* Error state */}
      {artifactsStatus === "error" && networkStatus === "online" && (
        <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4 text-destructive">
          Failed to load artifacts. Please try again.
        </div>
      )}

      {/* List */}
      {artifactsStatus === "loaded" && (
        <ArtifactList
          items={artifacts}
          search={artifactSearch}
          onSearchChange={handleSearchChange}
          onUpdate={handleUpdate}
          onDelete={handleDelete}
        />
      )}
    </div>
  )
}
