# Generated by Django 5.2.11 on 2026-03-25 16:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_convert_empty_emails_to_null"),
        ("workspaces", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransformationAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="dbt model name. Must be unique within scope+container.",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("tenant", "Tenant"),
                            ("workspace", "Workspace"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sql_content",
                    models.TextField(
                        help_text="dbt model SQL. Uses ref() within scope, direct table names across scopes."
                    ),
                ),
                (
                    "test_yaml",
                    models.TextField(blank=True, help_text="dbt schema test YAML for this model."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        help_text="The TransformationAsset this model supersedes for querying.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_by",
                        to="transformations.transformationasset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_assets",
                        to="users.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_assets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "name"],
            },
        ),
        migrations.CreateModel(
            name="TransformationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_runs",
                        to="users.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_runs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TransformationAssetRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("logs", models.TextField(blank=True)),
                ("test_results", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="transformations.transformationasset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_runs",
                        to="transformations.transformationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="transformationasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tenant__isnull", False), ("workspace__isnull", True)),
                    models.Q(("tenant__isnull", True), ("workspace__isnull", False)),
                    _connector="OR",
                ),
                name="transformation_asset_one_container",
            ),
        ),
        migrations.AddConstraint(
            model_name="transformationasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", False)),
                fields=("name", "scope", "tenant"),
                name="unique_asset_name_per_tenant_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="transformationasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("name", "scope", "workspace"),
                name="unique_asset_name_per_workspace_scope",
            ),
        ),
    ]
