# Generated by Django 5.2.11 on 2026-03-26 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformationasset",
            name="name",
            field=models.CharField(
                help_text="dbt model name. Must be unique within scope+container.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must be a valid dbt model name: lowercase letters, digits, and underscores, starting with a letter.",
                        regex="^[a-z][a-z0-9_]*$",
                    )
                ],
            ),
        ),
    ]
